gitlab_ssh_access_keys:
  - https://github.com/scardin.keys    # Sylvain Cardin
  - https://github.com/pikkle.keys     # Loïc Sérafin

gitlab_vm_dedicated_disk: /dev/sdb
gitlab_vm_dedicated_vg: gitlab-vg
gitlab_vm_dedicated_vg_fstype: ext4

gitlab_vm_volumes:
  - name: varlibdocker
    mount: /var/lib/docker
    size: 30G
  - name: gitlab
    mount: /srv/gitlab
    size: 2G
  - name: postgres
    mount: /srv/gitlab/postgresql
    size: 100%FREE

_gitlab_vm_device_mapper_path_of_item: "/dev/{{ gitlab_vm_dedicated_vg }}/{{ item.name }}"

gitlab_nfs_share:
  remote: cdh1files.epfl.ch:/u13477_cdh_emplus_001_files_nfs
  mount: '{{ gitlab_nfs_data_topdir }}'
