# Transcribed into Ansible-speak from https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

- name: GPG signing key for Docker packages
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Gather distribution name (LSB)
  ansible.builtin.setup:
    gather_subset: '!all'

- name: Docker repositories for Ubuntu
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      # https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
      deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
  register: _docker_apt_list

- name: Docker daemon and CLI
  ansible.builtin.apt:
    update_cache: >
      {{ _docker_apt_list is changed }}
    pkg:
    - docker-ce
    - docker-ce-cli

# No need to start the service - Ubuntu's package manager takes care of that
