- name: Access
  authorized_key:
    state: present
    user: root
    key: '{{ item }}'
  with_items:
    - '{{ gitlab_ssh_access_keys }}'  # As found in ../vars/gitlab-vm-vars.yml

- import_tasks: gitlab-vm-filesystems.yml
  tags: fs

- import_tasks: gitlab-vm-docker.yml
  tags: docker

- import_tasks: ntp.yml
  tags: ntp
