- include_vars: paths.yml  # From the top-level vars/ directory:
  tags: always

- name: "Single primary partition on {{ gitlab_vm_dedicated_disk }}"
  community.general.parted:
    device: "{{ gitlab_vm_dedicated_disk }}"
    label: gpt
    number: 1
    flags: [ lvm ]
    state: present

- name: "{{ gitlab_vm_dedicated_vg }} volume group"
  community.general.lvg:
    vg: "{{ gitlab_vm_dedicated_vg }}"
    pvs: "{{ gitlab_vm_dedicated_disk }}1"

- name: "Volumes on {{ gitlab_vm_dedicated_vg }}"
  community.general.lvol:
    vg: "{{ gitlab_vm_dedicated_vg }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    shrink: no
  with_items: "{{ gitlab_vm_volumes }}"

- name: "Filesystems on {{ gitlab_vm_dedicated_vg }}"
  community.general.filesystem:
    fstype: "{{ gitlab_vm_dedicated_vg_fstype }}"
    dev: "{{ _gitlab_vm_device_mapper_path_of_item }}"
  with_items: "{{ gitlab_vm_volumes }}"

- name: "Mount points for {{ gitlab_vm_dedicated_vg }}"
  ansible.posix.mount:
    path: "{{ item.mount }}"
    src: "{{ _gitlab_vm_device_mapper_path_of_item }}"
    fstype: "{{ gitlab_vm_dedicated_vg_fstype }}"
    state: mounted
  with_items: "{{ gitlab_vm_volumes }}"

- name: "NFS mount point"
  ansible.posix.mount:
    path: "{{ gitlab_nfs_share.mount }}"
    src: "{{ gitlab_nfs_share.remote }}"
    fstype: "nfs"
    opts: soft
    state: mounted
