- include_vars: "{{ item }}"
  tags: always
  with_items:
    - serving-vars.yml
    # From the top-level vars/ directory:
    - versions.yml
    - docker-networking.yml

- name: Common infrastructure
  import_tasks: infrastructure.yml
  tags: serving.infrastructure

- name: Serving images
  when: >
    inventory_hostname == "gitlabstaging"
  include_tasks:
    file: images.yml
    apply:
      tags:
        - images
  tags:
    - images
    - images.build
    - image.build

- name: Serving databases
  tags:
    - databases
    - databases.certs
    - postgres
    - postgresql
    - postgres.reload.staging
    - postgresql.reload.staging
    - postgres.monitoring
    - postgresql.monitoring
  include_tasks:
    file: databases.yml
    apply:
      tags:
        - databases
