- gather_facts: no
  hosts: gitlab-vm
  name: VM and infrastructure configuration
  roles:
    - role: roles/gitlab-vm-infrastructure

- gather_facts: no
  hosts: gitlab-vm
  name: Unattended distribution upgrades
  # https://github.com/jnv/ansible-role-unattended-upgrades#for-ubuntu
  roles:
    - role: jnv.unattended-upgrades
  vars:
    unattended_remove_unused_dependencies: true
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: 03:00
    unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
      - 'o=Ubuntu,a=${distro_codename}'
      - 'o=Ubuntu,a=${distro_codename}-updates'
      - 'o=Ubuntu,a=${distro_codename}-proposed-updates'
    unattended_ignore_apps_require_restart: true
    unattended_dpkg_options: ["--force-confdef"]

- gather_facts: no
  hosts: gitlab-vm
  name: Backups
  roles:
    - role: roles/gitlab-backups

- gather_facts: no
  hosts: all_gitlabs
  name: Serving containers
  roles:
    - role: roles/gitlab-serving

- gather_facts: no
  hosts: gitlab-vm
  name: Træfik
  roles:
    - role: roles/gitlab-traefik

- gather_facts: no
  hosts: localhost
  name: Operator workstation configuration for aws-cli
  roles:
    - role: roles/localhost-aws
