- gather_facts: no
  hosts: all
  name: VM and infrastructure configuration
  roles:
    - role: roles/gitlab-vm-infrastructure

### TODO: later we can have more roles, e.g.
# - gather_facts: no
#   hosts: all
#   name: gitlab deployment
#   roles:
#     - role: roles/gitlab

