- gather_facts: no
  hosts: gitlab-vm
  name: VM and infrastructure configuration
  roles:
    - role: roles/gitlab-vm-infrastructure

- gather_facts: no
  hosts:
    - gitlabstaging
    - gitlabprod
  name: Serving containers
  roles:
    - role: roles/gitlab-serving

- gather_facts: no
  hosts:
    - gitlabprod
  name: Træfik
  roles:
    - role: roles/gitlab-traefik
