- gather_facts: no
  hosts: gitlab-vm
  name: VM and infrastructure configuration
  roles:
    - role: roles/gitlab-vm-infrastructure

- gather_facts: no
  hosts:
    - gitlabstaging
    - gitlabprod
  name: User-facing features
  roles:
    - role: roles/gitlab-serving
