traefik_acme_state_dir: /srv/gitlab/secrets/acme

traefik_static_config_file: /srv/gitlab/config/traefik/traefik.yml
traefik_staging_dynamic_config_file: "{{ traefik_dynamic_config_dir }}/staging.yml"
traefik_debug_dynamic_config_file: "{{ traefik_dynamic_config_dir }}/dashboard-and-debug.yml"
traefik_bluegreen_dynamic_config_file: "{{ traefik_dynamic_config_dir }}/bluegreen.yml"
traefik_extra_services_dynamic_config_file: "{{ traefik_dynamic_config_dir }}/extra-services.yml"

## turn these on with care (e.g. traefik_debug exposes private stuff to the Internets)
# traefik_debug: true
# traefik_letsencrypt_staging: true

# https://community.containo.us/t/ssh-proxy-from-traefik-to-lxc/608/2
traefik_tcp_rule_catch_all: "HostSNI(`*`)"
